#!/bin/bash
pattern='/\G[^\x00-\x7F]/gm'
title=$(playerctl metadata --format '{{ title }}')
count=$(echo -n "$title" | wc -c)
if [ -z "$title" ]; then
	echo "Not Playing";
else
	if [ "$count" -le 25 ]; then
        echo $title
	else
		echo ${title:0:25}...
	fi
fi
#	else
#		if [[ "$title" =~ [^\x10-\x7F] ]]; then
#			echo "$(playerctl metadata --format '{{ title }}' | awk '{ print substr($) }')..."
#        elif [[ "$title" -le 15 ]]; then
#            echo $(playerctl metadata --format '{{ title }}' | awk '{print $1, $2}')
#        else
#	    	echo "$(playerctl metadata --format '{{ title }}' | awk '{print $1, $2, $3}')..."
#		fi
#	fi
#fi
