#!/bin/bash
tmp_dir="/tmp/eww/"
tmp_cover_path=$tmp_dir/cover.png

if [ ! -d $tmp_dir ]; then
	mkdir -p $tmp_dir
fi

if [ -n $(playerctl metadata 2>/dev/null) ]; then
	cp $HOME/.config/eww/images/empty.png $tmp_cover_path
	exit
fi

[[ -n $(playerctl metadata | grep -i "chromium") ]] && cp $HOME/.config/eww/images/chrome.png $tmp_cover_path && exit
[[ -n $(playerctl metadata | grep -i "vlc") ]] && cp $HOME/.config/eww/images/vlc.png $tmp_cover_path && exit

if [ $(playerctl metadata mpris:artUrl) ]; then
	artlink="$(playerctl metadata mpris:artUrl | sed -e 's/open.spotify.com/i.scdn.co/g')"
	curl -s "$artlink" --output $tmp_cover_path
fi
