#!/bin/bash

cur_vol=$(pamixer --get-volume)

up() {
  kill -44 $(pidof dwmblocks)
  pamixer --increase 5
  # volnoti-show $(pamixer --get-volume)
}

down() {
  kill -44 $(pidof dwmblocks)
  pamixer --decrease 5
  # volnoti-show $(pamixer --get-volume)
}

sset() {
  kill -44 $(pidof dwmblocks)
  pamixer --set-volume $1
  # volnoti-show $(pamixer --get-volume)
}

mute() {
  kill -44 $(pidof dwmblocks)
  [[ $(pamixer --get-mute) == "false" ]] && pamixer --mute || pamixer --unmute
  # if [[ $(pamixer --get-mute) == "false" ]];
  # then
    # pamixer --mute
    # volnoti-show -m
  # else
    # pamixer --unmute
    # volnoti-show $(pamixer --get-volume)
  # fi
}

case $# in
  1)
    case $1 in
      "up")
        up
        ;;
      "down")
        down
        ;;
      "mute")
        mute 
        ;;
      *)
        echo "Inalid argument!"
        exit
        ;;
    esac
    ;;
  2)
    case $1 in
      "sset")
        sset $2
        ;;
      *)
        echo "Invalid argument!"
        exit
        ;;
    esac
    ;;
  *)
    echo "Too many arguments!"
    exit
    ;;
esac
