#!/bin/bash

# maim -s | xclip -selection clipboard -t image/png && notify-send "Screenshot" "Copied to Clipboard" -i flameshot
# scrot --silent '/tmp/%F_%T_$wx$h.png' -e 'xclip -selection clipboard -target image/png -i $f' && notify-send "Screenshot" "Copied to Clipboard" -i flameshot
scrot --silent -d 5 '/tmp/%F_%T_$wx$h.png' -e 'xclip -selection clipboard -target image/png -i $f' 

