#!/bin/bash

manual=$(man -k . | awk '{print $1}' | 
  rofi -i -no-custom -matching prefix -dmenu -p "Manuals" -theme ~/.config/rofi/launcher/manuallauncher.rasi)
[[ -n "$manual" ]] && man -Tpdf $manual | zathura -
