#!/bin/bash

cat <<EOF | xmenu | sh &
Applications
	IMG:/usr/share/icons/hicolor/48x48/apps/firefox.png				  Firefox						firefox
	IMG:/usr/share/icons/breeze-dark/apps/48/kcalc.svg				  Calculator				kcalc	
	IMG:/usr/share/icons/hicolor/48x48/apps/spotify.png				  Spotify						spotify
	IMG:/usr/share/icons/hicolor/48x48/apps/telegram.png			  Telegram Desktop	telegram-desktop
	IMG:/usr/share/icons/hicolor/48x48/apps/sublime-text-3.png	Sublime Text 3		subl3
Launch Terminal 		st
Screenshot
	Window						screenshot
	Selection					screenshot_s
Lockscreen					betterlockscreen -l
Shutdown						poweroff
Reboot							reboot
EOF
