#!/bin/bash

[[ -d $HOME/Pictures/Screenshots ]] || mkdir -p $HOME/Pictures/Screenshots

file="$HOME/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%M-%S).png" 
scrot --silent $file &&
  xclip -selection clipboard -t image/png "$file" &&
    notify-send "Screenshot" "Saved to Pictures" -i $file 
