#!/bin/bash

[[ -d $HOME/Pictures/Screenshots ]] || mkdir -p $HOME/Pictures/Screenshots

file=$(mktemp --suffix '.png')
import -silent -quiet $file && xclip -selection clipboard -t image/png $file && notify-send "Screenshot" "Copied to clipboard" -i $file 
