#!/bin/bash

keyword=$(xclip -out -selection primary)
browser="firefox"
# 1=google 2=duckduckgo 3=bing
search_engine=3


if [[ $search_engine -eq 1 ]]; then
  notify-send "Google" "Search for '$keyword'" -t 3000
  $browser "https://google.com/search?q=$(echo $keyword | tr " " "+")"
elif [[ $search_engine -eq 2 ]]; then
  notify-send "Duckduckgo" "Search for '$keyword'" -t 3000
  firefox "https://duckduckgo.com/?q=$(echo $keyword | tr " " "+")"
elif [[ $search_engine -eq 3 ]]; then
  notify-send "Bing" "Search for '$keyword'" -t 3000
  $browser "https://bing.com/search?q=$(echo $keyword | tr " " "+")"
fi

