#!/bin/bash

wallno=$(ls $HOME/wallpapers | wc -l)	# get number of wallpapers available
randno=$(python3 -S -c "import random; print(random.randint(1, ($wallno + 1)))")	# generate a random number between 1 and $wallno
# python's randint doesn't include the last number

bg="$HOME/wallpapers/wall$randno.jpg"
feh --bg-scale "$bg" 
