#!/bin/sh

declare -A menu

menu["Launch_Terminal"]='st'
menu["Launch_Firefox"]='firefox'
menu["Launch_Calculator"]='kcalc'
menu["Launch_Neovim"]='st -e nvim'
menu["Screenshot_Window"]='screenshot'
menu["Screenshot_Selection"]='screenshot_s'

cmd=$( echo ${!menu[@]} | tr " " "\n" | tr "_" " " | sort | xmenu )
key=$( echo $cmd | tr " " "_" )

$( ${menu["$key"]} )
