#!/bin/bash

line=0

notification=""

build() {
  [[ -n "$APP_NAME" ]] && notification+="{\n\"App\": \"$APP_NAME\",\n"
  [[ -n "$APP_ICON" ]] && notification+="\"Icon\": \"$APP_ICON\",\n"
  [[ -n "$ID" ]] && notification+="\"ID\": \"$ID\",\n"
  [[ -n "$SUMMARY" ]] && notification+="\"Summary\": \"$SUMMARY\",\n"
  [[ -n "$BODY" ]] && notification+="\"Body\": \"$BODY\",\n"
  [[ -n "$ACTION" ]] && notification+="\"Action\": \"$ACTION\",\n"
  [[ -n "$URGENCY" ]] && notification+="\"Urgency\": \"$URGENCY\",\n"
  [[ -n "$TIMEOUT" ]] && notification+="\"Timeout\": \"$TIMEOUT\"\n}\n"
  echo -e "$notification"
  echo -e "$notification" >> ~/.notifications/notif 
}

tiramisu -s 2>/dev/null | while read -r value
do
  case $line in
    0 )
      APP_NAME="${value//\"}"
      ;;
    1 )
      APP_ICON=$value
      ;;
    2 )
      ID=$value
      ;;
    3 )
      SUMMARY=$value
      ;;
    4 )
      BODY=$value

      ;;
    5 )
      ACTION=$value
      ;;
    6 )
      URGENCY=$value
      ;;
    7 )
      TIMEOUT=$value
      ;;
    8 )
      notification=""
      build
      ((notification_id+=1))
      line=-1
      ;;
  esac
  ((line+=1))
done
